[package]
name = "bevy_jfa"
description = "The Jump Flooding Algorithm (JFA) for Bevy."
authors = ["dataphract"]
version = "0.1.0"
edition = "2021"

[features]
default = ["wgpu-profiler"]

[dependencies]
#bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "a0af066" }
bevy = { path = "../bevy" }
bitflags = "1"
wgpu-profiler = { version = "0.8", optional = true }

[profile.dev]
opt-level = 3
