[package]
name = "cube"
authors = ["dataphract"]
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", rev = "f969c62" }
bevy_jfa = { path = "../.." }
